{
 "title": "Service Health Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Ключевые показатели", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Общий RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"telegram-analytics-app\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"telegram-analytics-app\"}[5m])) by (le)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Нагрузка на БД (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opcounters[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Задержка Event Loop (Lag)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=\"telegram-analytics-app\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Детализация по показателям", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Общий RPS по ручкам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"telegram-analytics-app\"}[1m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Latency по ручкам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"telegram-analytics-app\"}[5m])) by (le, route)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Нагрузка на БД (RPS) по типам запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opcounters[1m])) by (legacy_op_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Коды статуса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"telegram-analytics-app\"}[1m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Состояние алертов",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 } }
 ]
}